In [1]:
#You declare the variable without type.
a = 3
b = True
c = 'String!'
print(a,b,c)

3 True String!


In [2]:
print(5/2)

# these 2 lines yield the same result
# 2 ways to yield integer result from division operation
print(int(5/2))
print(5//2)


# Students can also use divmod(dividend, divisor) to get a tuple containing (integerresult, remainder)
print(divmod(5, 2))


2.5
2
2
(2, 1)


In [3]:
#Loops
arr = [1,2,3,4,5]
print('show array with for in')
for x in arr:
    print(x)
print('show array with for in range')
for x in range(len(arr)):
    print(arr[x])
print('show even numbers')
for x in arr:
    if x%2 == 0:
        print(x)


show array with for in
1
2
3
4
5
show array with for in range
1
2
3
4
5
show even numbers
2
4


In [3]:
# Array Indexing:
arr = [0,1,2,3,4,5]
print(arr[0:3])

import numpy as np


origMat = np.array(arr)
mat = np.copy(origMat)
print(mat)
mat[0:3] = 0
print(mat)
mat = np.copy(origMat)
mat[(mat%2==0)] = -1
print(mat)

[0, 1, 2]
[0 1 2 3 4 5]
[0 0 0 3 4 5]
[-1  1 -1  3 -1  5]


In [2]:
origMat = np.array([
                   [1,2,3,4,5],
                   [1,2,3,4,5],
                   [1,2,3,4,5]
                   ])
mat = np.copy(origMat)
print(mat)
mat[1:3,1:3] = 0
print(mat)

NameError: name 'np' is not defined

In [ ]:
arrZeros = np.zeros((6,5))
arrOnes =np.ones((6,5))
print(arrZeros)
print(arrOnes)
print(arrOnes.shape)
print(arrOnes.shape[0])

In [ ]:
# Shows the fact that Python uses KEYWORD ARGUMENTS as well as the traditional positional arguments.
## Notice that: in the output of the first and second call to function fun are the same.
## In the second call (using keywords arguments), sorting arguments is not needed.


def fun(x,y,z):
    print (x,y,z)
    
fun(1,2,3);
fun(z=3,y=2,x=1)

In [ ]:
#instead of NULL: None

x = None
if (x==None):
    print('x is None')
